channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - gffutils
  - pip
  - pip:
    - pandas
    - matplotlib
    - numpy
    - seaborn
    - argparse
    - typing
    - re
    - collections
